### ISSUE TITLE
Mac build: Do not use X directly

### ISSUE THREAD

**Issue by aganm** [edubart/miniphysfs#1]
Hey!

I'm trying to get this working for linux/win/mac, when I get to the mac build, I set up a .c file for the implementation and a .m file for the platform implementation and feed that to clang c compiler.

I'm getting errors because of that
https://github.com/edubart/miniphysfs/blob/21915578107d83fd1693ae119d0f46baac7f4470/miniphysfs.h#L4291-L4295

What is this? Is the mac support incomplete?

**Comment by edubart** [comment]
Hey, unfortunately I don't have a Mac OS to test. But I've heard people using miniphysfs on Mac with success.

One ideia, try to just everything in one `.m` file, that is, collapse the C into the M file, and remove the C file.

Also you did not share the compiler errors..

**Comment by aganm** [comment]
Oh, the errors were meaningless, just the compiler trying to parse `Do not use malloc() directly.` because it was pasted directly in the code.

But your idea fixed the problem. Thanks!
