### ISSUE TITLE
Mac help

### ISSUE THREAD

**Issue by konsumer** [edubart/miniphysfs#3]
Pardon me, if this is dumb, as I am not great with C, but I can't build on Mac.

I'm pretty sure I don't understand the instructions (put what code in .m file?) I saw #1 but I still don't get it. Here is what I did:

- Copy [miniphysfs.h](https://github.com/edubart/miniphysfs/blob/main/miniphysfs.h) in [my simple C project](https://github.com/notnullgames/null0/tree/main/runtimes/native)
- add this code at the top of my main.c:

```c
#define PHYSFS_IMPL
#define PHYSFS_PLATFORM_IMPL
#define PHYSFS_SUPPORTS_ONLY_ZIP
#include "miniphysfs.h"
```

I get this error:

```
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:8:
/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:523:1: error: expected identifier or '('
@class NSString, Protocol;
```

and a bunch more that are similar.

I am trying to just compile a plain C program that runs on mac/win/linux but .m files are ObjectiveC, right?

**Comment by edubart** [comment]
Mac OS should have 2 implementation files:

* `miniphysfs.m`, define `PHYSFS_PLATFORM_IMPL` only on it.
* `miniphysfs.c` define `PHYSFS_IMPL` only on it, plus any additional configuration.

As said in the readme in MacOS you need to define `PHYSFS_PLATFORM_IMPL` in a separate a `.m`, because it enables use of Objetive C source code.

**Comment by konsumer** [comment]
I don't think I understand. I think I followed those directions [here](https://github.com/konsumer/miniphysfs-test) in a minimal test project. I get this error when I build:

```
Undefined symbols for architecture arm64:
  "_PHYSFS_deinit", referenced from:
      _main in main.c.o
  "_PHYSFS_getErrorByCode", referenced from:
      _main in main.c.o
  "_PHYSFS_getLastErrorCode", referenced from:
      _main in main.c.o
  "_PHYSFS_init", referenced from:
      _main in main.c.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [null0] Error 1
make[1]: *** [CMakeFiles/null0.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by konsumer** [comment]
Do I need to do something different in my cmake config? Is there a way to use a single source layout, so it will build for linux/mac/windows (like via defines or something?)

**Comment by edubart** [comment]
Mac OS need multiple files because it requires Objective C. If you don't know how to setup and build C and Objective-C files you probably should not use this library, try official PhysFS then.

**Comment by konsumer** [comment]
ok, I can use physfs. I will say this seems a little bit disingenuous (from README):

> This is the PhysFS contained in a single header to be bundled in C/C++ applications with ease.

Like it's not a single header, or easy to use, compared to any other library I have worked with, at least on mac.

> If you don't know how to setup and build C

Well, I dunno if I would say that. I have a lot of C projects I work on, that all build fine, on many platforms. It's not your job to help me use your free and open-source library, which I totally appreciate. I make a lot of open-source stuff too, and it can be challenging to support it all, sometimes, but I agree it may not be a great fit for my use-case.
